# Whether or not players collide with each other (true/false)
playerCollisions: true

# The Y level of the highest water block in the sea, players that fall into the sea will drown (specified below)
seaLevel: 105

# How long it takes for players to drown after falling into the sea (in seconds)
drownTime: 5

# The villager profession of the merchants
merchantProfession: LeatherWorker

# The villager profession of the captains
captainProfession: Armorer

# If this is true, using the command "/leave" will leave the current Treasure Wars game.
enableLeaveCommand: true